'use client';
import { useState } from 'react';
import dynamic from 'next/dynamic';
import ContactForm from '@/components/contact-form';
import Toolkit from '@/components/toolkit';
import Experience from '@/components/experience';
import { PageProgress, CursorGlow, ParallaxLayer, TiltCard, Magnetic, RevealHeading } from '@/components/interactive-effects';
import { motion, useReducedMotion } from 'motion/react';
import { ArrowUpRight, ArrowDown, Download, Code2, Layers3, Sparkles, Menu, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogTitle, DialogTrigger } from '@/components/ui/dialog';

const HeroScene = dynamic(() => import('@/components/hero-scene'), { ssr: false, loading: () => <div className="scene-loading">Entering the third dimension…</div> });

const projects = [
    { name: 'Shortlist', kind: 'FULL STACK APPLICATION', description: 'Your job search. Finally, in one place.', stack: ['Next.js', 'TypeScript', 'Prisma', 'PostgreSQL'], type: 'dashboard', detail: 'A job application and interview tracker with per-user applications, stage filters, interview scheduling, notes, reminders, and analytics. Built with Next.js route handlers, Prisma, PostgreSQL, and ownership-checked mutations.', features: ['Job applications, interviews, and reminders in one workspace', 'Database-backed sessions and per-user data ownership', 'Interactive demo available without an account'], repo: 'https://github.com/Ralphonk/shortlist', live: 'https://shortlist-tracker.vercel.app', image: '/shortlist-preview.png' },
    { name: 'RoleLens', kind: 'AI × FULL STACK', description: 'Find the fit. Understand the gaps.', stack: ['Next.js', 'Express', 'Gemini', 'PostgreSQL'], type: 'resume', detail: 'A resume-to-job matcher combining Gemini structured analysis with application-calculated scores. It supports text-based PDF extraction, evidence-based skill feedback, saved resume versions, and match history. Scores are advisory document comparisons, not hiring predictions.', features: ['PDF extraction and structured AI analysis', 'Skill-gap insights with supporting evidence', 'Saved resume versions and revocable cookie sessions'], repo: 'https://github.com/Ralphonk/rolelens', live: 'https://rolelens-resume.vercel.app', image: 'https://raw.githubusercontent.com/Ralphonk/rolelens/main/docs/images/workspace.png' },
    { name: 'Fold Studio', kind: '3D × INTERACTIVE EXPERIENCE', description: 'An idea that unfolds in your hands.', stack: ['Three.js', 'JavaScript', 'WebGL'], type: 'fold', detail: 'An independent iPhone 18 Fold concept with a scroll-driven 3D hero and interactive configurator. Explore folding from 0 to 180 degrees, camera presets, finishes, capacities, and downloadable configuration. This is a concept, not an official Apple product; imagery and specifications are illustrative.', features: ['Articulated 3D hinge and scroll-driven storytelling', 'Touch, drag, zoom, and keyboard camera controls', 'Live finishes, folding, and configuration export'], repo: 'https://github.com/Ralphonk/iphone-18-fold-concept', live: 'https://iphone-18-fold-concept-d5fe.vercel.app/', image: 'https://raw.githubusercontent.com/Ralphonk/iphone-18-fold-concept/main/dist/images/editorial.png' },
    { name: 'Zuperior', kind: 'WEB EXPERIENCE', description: 'A digital front door to global markets.', stack: ['Website', 'Fintech'], type: 'zuperior', detail: 'A website for a forex, CFD, and crypto trading platform, presenting its accounts, market tools, and platform ecosystem. Explore the live website below.', features: ['Trading platform and account information', 'Market tools and calculators', 'Product ecosystem presentation'], repo: '', live: 'https://www.zuperior.com/', image: '/zuperior-preview.png' },
];

function ProjectArt({ type }: { type: string }) {
    const project = projects.find(p => p.type === type);
    if (!project?.image) return null;
    const suppliedScreenshot = type === 'dashboard' || type === 'zuperior';
    const descriptions: Record<string, string> = {
        dashboard: 'Shortlist demo workspace showing job applications, interviews, and the application pipeline',
        zuperior: 'Zuperior trading website homepage with the Think Superior, Trade Zuperior hero',
        resume: 'RoleLens resume and job matching workspace',
        fold: 'Fold Studio conceptual foldable phone, illustrative concept imagery',
    };
    return <div className={'art art-real art-' + type + (suppliedScreenshot ? ' art-screenshot' : '')}>
        <img src={project.image} alt={descriptions[type] || project.name} loading="lazy" />
        {!suppliedScreenshot && <span className="real-caption">{type === 'fold' ? 'INDEPENDENT CONCEPT · THREE.JS' : 'RESUME → INSIGHTS'}</span>}
    </div>;
}

export default function Home() {
    const [menu, setMenu] = useState(false); const reduced = useReducedMotion();
    return <main id="top"><PageProgress /><CursorGlow />

        <header className="header wrap"><a href="#top" className="brand" aria-label="Portfolio home">uj<span>®</span></a><nav className={menu ? 'nav nav-open' : 'nav'} aria-label="Main navigation">{['Work', 'Experience', 'About', 'Contact'].map(x => <a key={x} href={'#' + x.toLowerCase()} onClick={() => setMenu(false)}>{x}</a>)}</nav><a className="header-cta" href="#contact">Let’s talk <ArrowUpRight size={16} /></a><button className="menu-toggle" aria-label={menu ? 'Close navigation' : 'Open navigation'} aria-expanded={menu} onClick={() => setMenu(!menu)}>{menu ? <X /> : <Menu />}</button></header>
        <section className="hero wrap">
            <ParallaxLayer depth={-.3} className="hero-copy-depth"><motion.div className="hero-copy" initial={reduced ? false : { opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .7 }}><p className="eyebrow"><span className="small-cross">✳</span> UMESH JOSHI / FULL STACK DEVELOPER</p><RevealHeading /><p className="hero-description">I’m Umesh. I build full stack applications, AI-powered tools, and interactive web experiences. I care about everything you see and everything you don’t.</p><div className="hero-actions"><Magnetic><Button asChild><a href="#work">Explore my work <ArrowDown size={17} /></a></Button></Magnetic><Button asChild variant="outline" className="resume-button"><a href="/Umesh-Joshi-Resume.pdf" download="Umesh-Joshi-Resume.pdf">Download my resume <Download size={17} /></a></Button></div></motion.div></ParallaxLayer>
            <div className="hero-visual hero-3d"><ParallaxLayer depth={.85} className="hero-scene-depth"><HeroScene /></ParallaxLayer></div>
            <div className="hero-footer"><span>CRAFTED AT THE INTERSECTION OF DESIGN & ENGINEERING</span><a href="#work">SCROLL TO DISCOVER <ArrowDown size={13} /></a></div>
        </section>
        <Toolkit />
        <section id="work" className="work wrap section"><div className="section-heading"><div><p className="eyebrow">01 / SELECTED WORK</p><h2>Built to make<br /><span>a difference.</span></h2></div><p>From database to interface.<br />From useful tools to playful experiences.<br /><small>Explore the product. Look under the hood.</small></p></div><div className="project-grid">{projects.map((p, i) => <motion.article className={'project project-' + i} key={p.name} initial={reduced ? false : { opacity: 0, y: 55, filter: "blur(7px)" }} whileInView={{ opacity: 1, y: 0, filter: "blur(0px)" }} viewport={{ once: true, amount: .12 }} transition={{ duration: .5 }}><Dialog><DialogTrigger asChild><button className="project-trigger" aria-label={`Explore ${p.name} project`}><TiltCard><ProjectArt type={p.type} /><span className="project-explore">Explore project <ArrowUpRight size={17} /></span></TiltCard><div className="project-info"><div><p className="project-kind">{p.kind} </p><h3>{p.name}<span>{p.description}</span></h3></div><span className="project-arrow"><ArrowUpRight size={23} /></span></div></button></DialogTrigger><DialogContent header={<><p className="eyebrow">PROJECT {String(i + 1).padStart(2, '0')} / {p.kind}</p><DialogTitle className="dialog-title">{p.name}</DialogTitle><p className="dialog-subtitle">{p.description}</p></>} footer={<div className="project-links"><Button asChild><a href={p.live} target="_blank" rel="noopener noreferrer">View live site <ArrowUpRight size={16} /></a></Button>{p.repo && <a href={p.repo} className="text-link" target="_blank" rel="noopener noreferrer">Explore source <ArrowUpRight size={16} /></a>}</div>}><div className="dialog-art"><ProjectArt type={p.type} /></div><DialogDescription className="dialog-description">{p.detail}</DialogDescription><p className="dialog-section-label">PROJECT HIGHLIGHTS</p><ul className="project-features">{p.features.map(f => <li key={f}>{f}</li>)}</ul></DialogContent></Dialog><div className="tags">{p.stack.map(t => <span key={t}>{t}</span>)}</div></motion.article>)}</div><div className="more-projects"><a href="https://github.com/Ralphonk" target="_blank" rel="noopener noreferrer">And many more on GitHub <ArrowUpRight size={16} /><span className="sr-only"> (opens in a new tab)</span></a></div></section>
        <Experience />
        <section id="about" className="about section"><div className="wrap about-grid"><div><p className="eyebrow">03 / BEHIND THE WORK</p><h2>A builder’s mind.<br /><span>A designer’s eye.</span></h2><p className="about-copy">I’m Umesh Joshi, a full stack developer interested in how useful products come together, from data models and APIs to the interface someone touches every day.</p><p className="about-copy">Recently, that has meant shipping payment flows, KYC journeys, real-time trading interfaces, and the services behind them. I’m at my best when a product needs dependable backend thinking and an interface people can understand immediately.</p><div className="social-links"><a href="https://github.com/Ralphonk" target="_blank" rel="noopener noreferrer">GitHub <ArrowUpRight size={15} /></a><a href="https://www.linkedin.com/in/umesh-joshi1/" target="_blank" rel="noopener noreferrer">LinkedIn <ArrowUpRight size={15} /></a></div></div><div className="principles">{[{ icon: Code2, title: 'Engineering with intention', text: 'Readable code, thoughtful architecture, and interfaces that hold up beyond the first impression.' }, { icon: Layers3, title: 'Every detail has a job', text: 'Clear hierarchy, accessible interactions, and responsive layouts that feel at home on any screen.' }, { icon: Sparkles, title: 'A little unexpected', text: 'Meaningful motion and playful moments that give a useful product its own personality.' }].map((p, i) => <div className="principle" key={p.title}><p.icon size={23} /><div><span>0{i + 1}</span><h3>{p.title}</h3><p>{p.text}</p></div></div>)}</div></div></section>
        <section id="contact" className="contact wrap section"><div className="contact-intro"><p className="eyebrow">04 / WHAT’S NEXT?</p><h2>Big idea?<br />Good instinct.<br /><span>Let’s talk.</span></h2><p className="contact-lead">A thoughtful product. An ambitious team.<br />A challenge worth figuring out.</p><a className="contact-email" href="mailto:umeshjoshi.dev@gmail.com">umeshjoshi.dev@gmail.com <ArrowUpRight size={19} /></a><div className="social-links"><a href="https://www.linkedin.com/in/umesh-joshi1/" target="_blank" rel="noopener noreferrer">LinkedIn <ArrowUpRight size={15} /></a><a href="https://github.com/Ralphonk" target="_blank" rel="noopener noreferrer">GitHub <ArrowUpRight size={15} /></a></div><span className="contact-stamp" aria-hidden="true">LET’S MAKE<br /><em>SOMETHING</em><br />MATTER. <Sparkles size={26} /></span></div><ContactForm /></section>
        <footer className="footer wrap"><a href="#top" className="brand" aria-label="Back to top">uj<span>®</span></a><span>© 2026 Umesh Joshi. Built with intention.</span><a href="#top">BACK TO TOP <ArrowUpRight size={14} /></a></footer>
    </main>;
}
